--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/BetterMute
build-by-default: true
branches:
- master
projects:
  BetterMute:
    path: ""
    icon: "icon.gif"
    libs:
      - src: poggit.pmmp.io/ci/supercrafter333/DiscordWebhooksX/DiscordWebhooksX
        version: ^1.0.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...